# Параметры зоны ТЦ и внешней зоны
r0: 0.0  # ° градусы
r1: 6.0  # ° градусы
r_stp: 0.25  # ° градусы
profile_resolution: 0.25  # ° градусы
min_dist: 0.25
extR1: r1  # ° градусы
extR2: 11.0  # ° градусы
PHI0: 0  # радианы
PHI1: 360  # радианы

delta: 0.55  # ° градусы
pNum: 8  # Число точек, на которые разбивается интервал шириной +-delta

# Ноль по шкале Цильсия в Кельвинах
baseK: 273.15

SLP: 1013.25  # Стандартное давление на уровне моря в GPa

LC: 43  # Число стандартных метеорологических уровней давления

MJD_HOUR: 1.0 / 24
MJD_TIME_INTERVAL: 6  # 6-ти часовой интервал (+-3 часа относительно даты центра ТЦ)

# Параметры фильтров
NUMBER_OF_CHANNELS: 35  # Минимальное число каналов радиометра, задействованное для расчёта среднего профиля вокруг ТЦ
ANOMALY_THRESHOLD_L1: 0  # Первый фильтруемый уровень профиля ТЦ
ANOMALY_THRESHOLD_L2: 33  # Последний фильтруемый уровень профиля ТЦ (LC - ANOMALY_THRESHOLD_L2)
ANOMALY_ACCEPTABLE_VAL: -1.5  # Максимально допустимое отклонение по любой точке профиля
MAX_PRESSURE_VAL: 1000  # Максимальное значение давления для ТЦ
SAT_IGNORE_LIST: [] #[ 'NOAA15', 'NOAA16', 'NOAA17', 'NOAA18', 'NOAA19']


relative_flg: True